backend:
    name: git-gateway
    branch: main

media_folder: "src/static/images/uploads"
public_folder: "/images/uploads"

collections:
    - label: "Pages"
      name: "pages"
      editor:
        preview: false
      files:
        - label: "Master"
          name: "master"
          file: "src/content/master.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Facebook URL", name: "facebookUrl", widget: "string" }
            - { label: "Instagram URL", name: "instagramUrl", widget: "string" }
            - { label: "Food Hygiene Rating URL", name: "foodHygieneRatingUrl", widget: "string" }
        - label: "Home Page"
          name: "home"
          file: "src/content/_index.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Subtitle", name: "subtitle", widget: "string" }
            - { label: "Hero Image", name: "hero", widget: "image" }
            - label: Images
              name: images
              widget: list
              fields: 
                - { label: "Image", name: "image", widget: "image" }
            - label: Testimonials
              name: testimonials
              widget: list
              fields: 
                - { label: "Text", name: "text", widget: "string" }
            - { label: "Content", name: "content", widget: "markdown" }
        - label: "Gallery"
          name: "gallery"
          file: "src/gallery/_index.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - label: Filters
              name: filters
              widget: list
              fields: 
                - { label: "Name", name: "name", widget: "string" }
            - label: Items
              name: items
              widget: list
              fields: 
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Text", name: "text", widget: "string" }
                - { label: "Text", name: "text", widget: "string" }
                - label: Bullets
                  name: bullets
                  widget: list
                  fields: 
                    - { label: "Bullets", name: "bullet", widget: "string" }
                - label: Images
                  name: images
                  widget: list
                  fields: 
                    - { label: "Image", name: "image", widget: "image" }
                    - { label: "Primary", name: "primary", widget: "boolean" }
                - label: Tags
                  name: tags
                  widget: list
                  fields: 
                    - { label: "Name", name: "name", widget: "string" }