backend:
    name: git-gateway
    branch: main

media_folder: "src/static/images/uploads"
public_folder: "/images/uploads"

collections:
    - label: "Pages"
      name: "pages"
      editor:
        preview: false
      files:
        - label: "Master"
          name: "master"
          file: "src/content/master.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Facebook URL", name: "facebookUrl", widget: "string" }
            - { label: "Instagram URL", name: "instagramUrl", widget: "string" }
            - { label: "Food Hygiene Rating URL", name: "foodHygieneRatingUrl", widget: "string" }
        - label: "Home Page"
          name: "home"
          file: "src/content/_index.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Subtitle", name: "subtitle", widget: "string" }
            - { label: "Hero Image", name: "hero", widget: "image" }
            - label: Images
              name: images
              widget: list
              fields: 
                - { label: "Image", name: "image", widget: "image" }
            - label: Testimonials
              name: testimonials
              widget: list
              fields: 
                - { label: "Text", name: "text", widget: "string" }